### ISSUE TITLE
eidlib - how do i detect card inserted, card exit for 24/7?

### ISSUE THREAD

**Issue by shamun** [KeejOow/eidlib#2]
I can read the card informations with following code:

```
package eid;
import be.belgium.eid.eidlib.BeID;
import be.belgium.eid.exceptions.EIDException;
public class Eid {
    public static void main(String[] args) {
        try {
            BeID eID = new BeID(true);
            // We fetch the information
            System.out.println("InformationRetrieval -- ID information:");
            System.out.println(eID.getIDData().toString());
            System.out.println("InformationRetrieval -- Address information:");
            System.out.println(eID.getIDAddress().toString());
            System.out.println("InformationRetrieval -- Photo is saved to file:");
            eID.getIDPhoto().writeToFile(eID.getIDData().getName());

        } catch (EIDException e) {
            System.err.println("InformationRetrieval eIDException -- "
                    + e.getMessage());
        } catch (Exception e) {
            System.err.println("InformationRetrieval exception -- "
                    + e.getMessage());
        }
    }
}
```

But i was asked if i can detect card inserted or card exited or card was invalidly inserted for a 24/7 monitoring project.

Can you please help me how to do that with eidlib?

**Comment by KrOverdulve** [comment]
Hi @shamun,

The AgeCheck example shows you how you could do this: https://github.com/KeejOow/eidlib/blob/master/eidlibsamples/src/be/belgium/eid/samples/AgeCheck.java

```
// Load the eID 
final BeID eID = new BeID(false);   // We don't allow test cards to verify their age
eID.enableCardListener(new CardAdapter() {
    public void cardInserted() {
        // We now check the age
        try {
            // Fetch birth date inserted card
            Date birthdate = eID.getIDData().getBirthDate();

            // Calculate what the upperbound of the birthdate is
            // (We ignore Leap Years)
            long timeBeforeNow = ageToCheck * 365 /* DAYS A YEAR */ 
                * 24 /* HOURS A DAY */ * 60 /* MINUTES PER HOUR */
                * 60 /* SEC/MINUTE */ * 1000;
            Date upperbound = new Date();
            upperbound.setTime(upperbound.getTime() - timeBeforeNow);

            // Check age
            if (birthdate.after(upperbound)) {
                System.out.println("AgeChecker -- Too young.");
            } else {
                System.out.println("AgeChecker -- OK.");
            }
        } catch (EIDException e) {
            e.printStackTrace(); 
            System.err.println("AgeChecker eIDException: -- " + e.getMessage());
        } catch (Exception e) {
            System.err.println("AgeChecker exception: -- " + e.getMessage());
        }

    }
});

// Keep on checking ages until QUIT is typed or process is ended
System.out.println("AgeChecker -- type QUIT to end program.");
String input = "";
while (!input.equalsIgnoreCase("QUIT")) {
    input = new Scanner(System.in).next();
}
```

**Comment by shamun** [comment]
I am getting always this following ERROR, even the card is inserted or exit, the informations are not keep getting scanned and the status of card insert/exit is not clear. 

What am i doing wrong please?

```
run:
AgeChecker -- type QUIT to end program.
javax.smartcardio.CardException: connect() failed
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:84)
    at be.belgium.eid.eidlib.SmartCard.connectCard(SmartCard.java:116)
    at be.belgium.eid.event.CardAlivePromptTask.run(CardAlivePromptTask.java:78)
Caused by: sun.security.smartcardio.PCSCException: SCARD_W_UNRESPONSIVE_CARD
    at sun.security.smartcardio.PCSC.SCardConnect(Native Method)
    at sun.security.smartcardio.CardImpl.<init>(CardImpl.java:100)
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:78)
    ... 2 more
javax.smartcardio.CardException: connect() failed
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:84)
    at be.belgium.eid.eidlib.SmartCard.connectCard(SmartCard.java:116)
    at be.belgium.eid.event.CardAlivePromptTask.run(CardAlivePromptTask.java:78)
Caused by: sun.security.smartcardio.PCSCException: SCARD_W_UNRESPONSIVE_CARD
    at sun.security.smartcardio.PCSC.SCardConnect(Native Method)
    at sun.security.smartcardio.CardImpl.<init>(CardImpl.java:100)
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:78)
    ... 2 more
```

Code:

```
package eid;
import be.belgium.eid.eidlib.BeID;
import be.belgium.eid.exceptions.EIDException;
import java.util.Date;
import java.util.Scanner;
import be.belgium.eid.eidlib.BeID;
import be.belgium.eid.event.CardAdapter;
import be.belgium.eid.exceptions.EIDException;

public class Eid {
    public static void main(String[] args) {
    try {
      final BeID eID = new BeID(true);  
      eID.enableCardListener(new CardAdapter() {
        public void cardInserted() {
          try {
            System.out.println(eID.getIDData().toString());
          } catch (EIDException e) { 
            System.err.println("AgeChecker eIDException: -- " + e.getMessage());
          } catch (Exception e) {
            System.err.println("AgeChecker exception: -- " + e.getMessage());
          }

        }
      });

      System.out.println("AgeChecker -- type QUIT to end program.");
      String input = "";
      while (!input.equalsIgnoreCase("QUIT")) {
        input = new Scanner(System.in).next();
      }

    } catch (NumberFormatException e) {
      System.err.println("AgeChecker -- Given argument should be an integral value.");
    }

    }
}
```
