### ISSUE TITLE
Status of card insert and exit is incorrect.

### ISSUE THREAD

**Issue by shamun** [KeejOow/eidlib#3]
I am getting always this following ERROR, even the card is inserted or exit, the informations are not keep getting scanned and the status of card insert/exit is not clear.

What am i doing wrong please?

```
run:
AgeChecker -- type QUIT to end program.
javax.smartcardio.CardException: connect() failed
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:84)
    at be.belgium.eid.eidlib.SmartCard.connectCard(SmartCard.java:116)
    at be.belgium.eid.event.CardAlivePromptTask.run(CardAlivePromptTask.java:78)
Caused by: sun.security.smartcardio.PCSCException: SCARD_W_UNRESPONSIVE_CARD
    at sun.security.smartcardio.PCSC.SCardConnect(Native Method)
    at sun.security.smartcardio.CardImpl.<init>(CardImpl.java:100)
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:78)
    ... 2 more
javax.smartcardio.CardException: connect() failed
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:84)
    at be.belgium.eid.eidlib.SmartCard.connectCard(SmartCard.java:116)
    at be.belgium.eid.event.CardAlivePromptTask.run(CardAlivePromptTask.java:78)
Caused by: sun.security.smartcardio.PCSCException: SCARD_W_UNRESPONSIVE_CARD
    at sun.security.smartcardio.PCSC.SCardConnect(Native Method)
    at sun.security.smartcardio.CardImpl.<init>(CardImpl.java:100)
    at sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:78)
    ... 2 more
```

Code:

```
package eid;
import be.belgium.eid.eidlib.BeID;
import be.belgium.eid.exceptions.EIDException;
import java.util.Date;
import java.util.Scanner;
import be.belgium.eid.eidlib.BeID;
import be.belgium.eid.event.CardAdapter;
import be.belgium.eid.exceptions.EIDException;

public class Eid {
    public static void main(String[] args) {
    try {
      final BeID eID = new BeID(true);  
      eID.enableCardListener(new CardAdapter() {
        public void cardInserted() {
          try {
            System.out.println(eID.getIDData().toString());
          } catch (EIDException e) { 
            System.err.println("AgeChecker eIDException: -- " + e.getMessage());
          } catch (Exception e) {
            System.err.println("AgeChecker exception: -- " + e.getMessage());
          }

        }
      });

      System.out.println("AgeChecker -- type QUIT to end program.");
      String input = "";
      while (!input.equalsIgnoreCase("QUIT")) {
        input = new Scanner(System.in).next();
      }

    } catch (NumberFormatException e) {
      System.err.println("AgeChecker -- Given argument should be an integral value.");
    }

    }
}
```

**Comment by shamun** [comment]
Hello, before you leave for vacation, can you please update the status kindly? We have to move forward once we get your confirmation the project is reaching its dead-line but still no feedback from you.

The application has to run in public location as kiosk, and when anyone insert id card we need to switch on micro-processors which is connected with many other real-time hardwares, then the id card is removed we have to repeat.

Waiting for your URGENT feedback. Thanks

**Comment by KrOverdulve** [comment]
Dear,

My apologies for not getting back to you sooner. Quite honestly I have no idea what might cause the issue you're having. The problem seems to stem from javax.smartcardio yielding errors connecting to your card.

If you find the solution to your problem and if the error lies within the library, I'd happily accept contributions. 

Regards,
Kristof.
